# Generated by Django 3.2.4 on 2021-07-10 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classified', models.CharField(choices=[('GMP', 'GMP'), ('ISO', 'ISO'), ('GDP', 'GDP'), ('GSP', 'GSP'), ('GMP TPBVSK', 'GMP TPBVSK'), ('Mỹ phẩm', 'Mỹ phẩm')], max_length=20, verbose_name='Phân loại')),
            ],
        ),
        migrations.CreateModel(
            name='SOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Tên quy trình')),
                ('code', models.CharField(max_length=64, verbose_name='Mã quy trình')),
                ('revision', models.IntegerField(verbose_name='Lần ban hành')),
                ('issued_date', models.DateField(null=True, verbose_name='Ngày ban hành')),
                ('recall', models.BooleanField(verbose_name='Thu hồi')),
                ('link', models.URLField(verbose_name='Link tài liệu')),
                ('dept_classified', models.CharField(max_length=225, verbose_name='Phân loại của Phòng')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department', to=settings.AUTH_USER_MODEL, verbose_name='Phòng ban hành')),
                ('permission', models.ManyToManyField(related_name='share', to='management.Classification', verbose_name='Phòng ban tiếp nhận')),
                ('sys_classified', models.ManyToManyField(related_name='classified', to=settings.AUTH_USER_MODEL, verbose_name='Phân loại của Chất lượng')),
            ],
        ),
    ]
