# Generated by Django 3.2.4 on 2021-06-08 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=10)),
                ('revision', models.IntegerField()),
                ('issued_date', models.DateField()),
                ('link', models.URLField()),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='QCdoc', to='management.regulation')),
                ('user', models.ManyToManyField(related_name='QCshare', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QA',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='QAdoc', serialize=False, to='management.regulation')),
                ('user', models.ManyToManyField(related_name='QAshare', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
