# Generated by Django 3.2.4 on 2021-07-12 03:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='classified',
            field=models.CharField(max_length=20, verbose_name='Phân loại'),
        ),
        migrations.AlterField(
            model_name='sop',
            name='permission',
            field=models.ManyToManyField(related_name='share', to=settings.AUTH_USER_MODEL, verbose_name='Phòng ban tiếp nhận'),
        ),
        migrations.AlterField(
            model_name='sop',
            name='sys_classified',
            field=models.ManyToManyField(related_name='sys_classified', to='management.Classification', verbose_name='Phân loại của Chất lượng'),
        ),
    ]
